import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/icons/favicon.ico"
};

export default function BaseLayout({children, title, icon}: Readonly<{children: React.ReactNode; title?: string; icon?: string}>) {
  return (
    <html lang="pt-BR">
      <head>
        <title>{title ?? metadata.title?.toString()}</title>
        <link rel="icon" type="image/x-icon" href={icon ?? metadata.icons?.toString()}></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen">
          <Navbar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
